version: '3.8'


services:
  web:
    command:
      [
        "sh",
        "-c",
        "pip3 install debugpy && python3 -m debugpy --listen 0.0.0.0:7777 manage.py runserver 0.0.0.0:8000",
      ]
    ports:
      - 8000:8000
      - 7777:7777
